### ISSUE TITLE
README fails to mention what `strace-analyzer`'s output looks like.

### ISSUE THREAD

**Issue by vi** [wookietreiber/strace-analyzer#34]
It shows how to call strace-analyzer, but does not show or explain what do I get from it.

---

By the way, does it work well for non-file things, like NETLINK sockets or tricky ioctls? README should also clarify what the tool can and what cannot do.

**Comment by wookietreiber** [comment]
Yes, you're right. I will address address this.

**Comment by wookietreiber** [comment]
I've updated the README, feel free to take a peek at it in the [**wip/next** branch](https://github.com/wookietreiber/strace-analyzer/blob/wip/next/README.md#strace-analyzer). I'm going to cut a new release soon anyway, that's why I'm still keeping it in that branch.

**Comment by vi** [comment]
Now it is more clear - it aggregates reads and writes by filepaths.

Should it be made more clear that mmap-based file access would not be counted?

> At the moment, strace-analyzer only analyzes reads and writes to the file system

Are there plans to implement more things? For example, networking sockets conversations may be aggregated in a similar way (including counters for usage of advanced features like AF_UNIX's SCM_RIGHTS).

**Comment by wookietreiber** [comment]
`mmap` is an open issue, see #7.

**Comment by wookietreiber** [comment]
> Are there plans to implement more things? For example, networking sockets conversations may be aggregated in a similar way (including counters for usage of advanced features like AF_UNIX's SCM_RIGHTS).

I myself don't intend to implement anything else at the moment. Feel free to contribute, though!

**Comment by wookietreiber** [comment]
Closing since the README is updated with the latest release.
